### ISSUE TITLE
"Outro" Translation

### ISSUE THREAD

**Issue by hugok79** [pardus/pardus-gnome-greeter#2]
https://github.com/pardus/pardus-gnome-greeter/blob/638f515dd3d7a329036315712990a3f188cbbc5f/data/po/pardus-gnome-greeter.pot#L48
The word "Outro" is a Portuguese word that means "Other" in English.
Is the word spelled right?

**Comment by fthaltun** [comment]
that's used here to mean like exit, last page in English.

**Comment by hugok79** [comment]
Like "Close" or "Exit"?

**Comment by fthaltun** [comment]
![Screenshot from 2023-08-28 14-15-25](https://github.com/pardus/pardus-gnome-greeter/assets/5893400/88507087-5c0c-4ad3-8c02-9dceada820f6)

like "Last Page", "Closing Page"

**Comment by hugok79** [comment]
@fthaltun  So what is the best translation for this word? How is it translated in Turkish?
Is "Miscellaneous"(Çeşitli) a good alternative?

**Comment by fthaltun** [comment]
We are using "Kapanış" in Turkish.

**Comment by hugok79** [comment]
Done. https://github.com/pardus/pardus-gnome-greeter/pull/5

**Comment by hugok79** [comment]
You can close this issue
